### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by iasj** [ctjhoa/spacevim#41]
Goodnight. It is not really clear what your plugin do. Can you explain? Maybe put this information in the readme?

Regards!

**Comment by ctjhoa** [comment]
Hi,
Sorry for the delay, spacevim goals is to mimic spacemacs which is an emacs distribution. So spacevim like spacemacs:
- define SPACE as vim leader and provides shorcuts around it.
- provides a leader guide to discover shortcuts
- provides a vim start screen
- is built with modularity in mind

I will try to had a similar explanation in the README.

**Comment by iasj** [comment]
A big thanks for the reply.

So it basicaly turns vim/neovim into some kind of "already configured editor", just like an IDE?

Well, if so, that might be great. I tested by renaming `~/config/nvim` to something else and then installing spacevim from scratch. It downloaded a lot of plugins, but after I got like a thousand error messages, and once I was busy I did not care to see what I was doing wrong (and I probably did something wrong).

I'll wait for these changes you told me about, and give it another try. I local friend is using spacevim, so I'll try to get some help also. And yeah, put some more explanation in the README, it is more likely people gonna use it if you do.

**Comment by ctjhoa** [comment]
Currently neovim is not supported (cf https://github.com/ctjhoa/spacevim/issues/40).

Take a look at http://spacemacs.org/ to get more explanation but yes it kinda IDE. I didn't took the time to add more documentation because this plugin was made for people frustrated to not have spacemacs behavior in vim. So in theory people using this plugin already know what are the shortcomings of vim compare to spacemacs.
Anyway I will add more documentation.

**Comment by iasj** [comment]
Oh. That's why I got the scary looking screen filled with error messages. Thanks, I'll wait then, 'cause no way I'm coming back to VIM. 

LOL. Regards, closing...
