### ISSUE TITLE
Roadmap: Boostrap layer system

### ISSUE THREAD

**Issue by ctjhoa** [ctjhoa/spacevim#7]
Hi there,

I think more and more of creating a layer manager like spacemacs. 
The problem is if I do that like spacemacs, there will be on each layer the installation of plugin(s) needed for that layer. So the spacevim users will not have the choice on implementations he wants. Even the plugin manager will be determined.

Spacemacs don't offer that choice and it's fine for me but I can understand that it's not the taste of everybody. It depends on how we see spacevim, is it just a helper to get the spacemacs bindings and fallback on which plugin are install or a complete solution batteries included.

I don't see other solution to get both flexibility and layer system. What's your thoughts on that?

/cc @jimmay5469 @sleexyz @ehamberg @nixmaniack @WuTheFWasThat

**Comment by WuTheFWasThat** [comment]
a big difference between spacemacs and spacevim for me personally is that i was new to emacs (had no emacs configuration, or even knowledge of emacs configuration), whereas i already had a pretty familiar vim setup, that i didn't want to just throw away.  my guess is this might be true for spacevim users in general?

also, as far as i'm aware, it's pretty unusual for vim plugins to install other vim plugins, or to force a plugin management system.  that said, if this project decides to go that route, my vote is for junegunn/vim-plug.  i think it's a bad idea though

i think we can still have the benefit of giving users a battery-included solution.  however, instead of being merely a plugin, you would basically just set up an entire vimrc and vim folder to be used, which installed all the best plugins.  that would mimic the way spacemacs simply takes over the `.emacs` folder

**Comment by ctjhoa** [comment]
Done in release 2.0.0!
